### ISSUE TITLE
imagePullSecrets

### ISSUE THREAD

**Issue by dyipon** [FairwindsOps/saffire#18]
Hi,

how can I auth to the backup repo? I have different imagePullSecrets for the secondary repo.

thanks

**Comment by sudermanjr** [comment]
You can create multiple imagePullSecrets, and reference them both in the pod spec.

**Comment by dyipon** [comment]
Didn't know that feature, but working, thanks!

**Comment by sudermanjr** [comment]
Glad you got it working!
